# Changes here will be overwritten by Copier
_src_path: /home/waylon/git/markata-blog-starter
author_email: ''
author_fullname: Ayla Walker
author_twitter: '@'
description: Ayla Walker dot com
project_name: aylawalker.com
python_package_import_name: aylawalker
url: https://aylawalker.com

